// <auto-generated />
using System;
using GttApiWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GttApiWeb.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20190212182722_added_caducidad_in_cert")]
    partial class added_caducidad_in_cert
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GttApiWeb.Models.Certificates", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("alias");

                    b.Property<bool>("caducado");

                    b.Property<bool>("eliminado");

                    b.Property<string>("email");

                    b.Property<string>("entidadEmisora");

                    b.Property<DateTime>("fechaCaducidad");

                    b.Property<string>("fichero64");

                    b.Property<long>("idOrga");

                    b.Property<string>("listaIntegraciones");

                    b.Property<string>("nombreArchivo");

                    b.Property<string>("nombreCliente");

                    b.Property<string>("numeroSerie");

                    b.Property<string>("observaciones");

                    b.Property<string>("password");

                    b.Property<string>("repositorio");

                    b.Property<string>("subject");

                    b.HasKey("id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("GttApiWeb.Models.Jira", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("component");

                    b.Property<string>("description");

                    b.Property<int>("issue_type");

                    b.Property<string>("pass");

                    b.Property<string>("proyect");

                    b.Property<string>("url");

                    b.Property<long>("user_id");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Jira");
                });

            modelBuilder.Entity("GttApiWeb.Models.Users", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("password");

                    b.Property<int>("role");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
